# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropModel', '0003_auto_20150918_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Bank_Account_Number', models.IntegerField(blank=True, null=True)),
                ('Payment_Date', models.DateField(blank=True, null=True, verbose_name=b'Date Paid')),
                ('Payment_Amount', models.IntegerField(blank=True, null=True)),
                ('Paid_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Receipt_Confirmation_Date', models.DateField(blank=True, null=True, verbose_name=b'Receipt Confirmed')),
                ('Notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name=b'Birth Date')),
                ('School', models.CharField(blank=True, max_length=50, null=True)),
                ('Class', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=2, null=True)),
                ('Zip', models.CharField(blank=True, max_length=5, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Teacher_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropModel.Gender')),
            ],
        ),
        migrations.RemoveField(
            model_name='bugcomment',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='bugfixrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='propcomment',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='proptype',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='propfin',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='propfin',
            name='property',
        ),
        migrations.RemoveField(
            model_name='proplisting',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentroll',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='rentroll',
            name='property',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
        migrations.DeleteModel(
            name='BugComment',
        ),
        migrations.DeleteModel(
            name='BugFixRequest',
        ),
        migrations.DeleteModel(
            name='BugFixStatus',
        ),
        migrations.DeleteModel(
            name='PropComment',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropFin',
        ),
        migrations.DeleteModel(
            name='PropListing',
        ),
        migrations.DeleteModel(
            name='PropModel',
        ),
        migrations.DeleteModel(
            name='PropStatus',
        ),
        migrations.DeleteModel(
            name='PropType',
        ),
        migrations.DeleteModel(
            name='RentRoll',
        ),
        migrations.DeleteModel(
            name='TimeFreq',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
