# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropModel', '0004_auto_20160411_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Paid_By',
        ),
        migrations.RemoveField(
            model_name='student',
            name='City',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='State',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Zip',
        ),
        migrations.AddField(
            model_name='payment',
            name='Pay_By',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
